spring.application.name=JavaQuestion
server.port=8080

app.jwt.secret=oodcmocowmocijqoujf032194j294jmg903kwx0K0K0K3019k039k0Ki0
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=86400000
